apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
      - name: backend
        image: devops-backend:k8s
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "appdb_dev"
        - name: DB_USER
          value: "appuser_dev"
        - name: DB_PASSWORD
          value: "S3cureDev!P@ssw0rd_2025"
        readinessProbe:
          httpGet: { path: /api/hello, port: 5000 }
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet: { path: /api/hello, port: 5000 }
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: devops
spec:
  selector: { app: backend }
  ports:
  - port: 5000
    targetPort: 5000
